version: "3.7"
services:
  app:
    ports:
      - "8000:80"
    build: ./web
    container_name: web
    volumes:
      - ./src/project:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - mysql

  mysql:
    image: "mariadb:10.3"
    container_name: mysql
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db/data:/var/lib/mysql"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
