version: '3.7'
services:
  app:
    ports:
      - "80:80"
      - "443:443"
    build: ./web
    container_name: web_app
    volumes:
      - ./src/projects:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_ENABLED: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_MAXNESTING_LEVEL: 1000
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
#      - VIRTUAL_Host=localhost
#      - VIRTUAL_Host=localhost,renewal
    depends_on:
      - db
  db:
    container_name: app_db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
#      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ./docker/db/log:/var/log
    ports:
      - 3306:3306

