version: '3.7'
services:
  web:
    # container_name: web_app
    build: ./docker/web
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - db
      - fpm
  fpm:
    # container_name: php_fpm
    build: ./docker/fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - db
  db:
    # container_name: app_db
    build: ./docker/db/
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

